### PR TITLE
`preinstall` step.

### PR DESCRIPTION
**Pull request by hemanth**
For `uglifyjs`

### CODE REVIEW

**Comment by LinusU** [comment]
You're missing a comma. And are you sure that you didn't mean `uglify-js`.

But why would you add this with `-g`, and why not just add it as a `"dependency"`?

**Comment by hemanth** [comment]
@LinusU Fixed the typo, we need `-g` or else it would be available on CLI as in the script, if not `-g` we need to give the path to `bin` in `node_modules` for `uglifyjs`

**Comment by LinusU** [comment]
Actually `npm run-script` prepends `$PATH` with `node_modules/.bin/` where it places symlinks to all installed dependencies.

**Comment by hemanth** [comment]
Ah, right. Closing it on behalf of #3

**Pull request closed without merging**
